Squashed commit of the following:
commit 24c75a9dc69c3b57092f10e87f616ed4e2e106a9
Author: Ratchet <250710285+RatchetStuff@users.noreply.github.com>
Date:   Sun Sep 20 19:46:09 2026 +0800

    feat(prepare.yml): Extend sleep time

commit f98c367b88376adcc8534e8d245f191946c3045a
Author: Ratchet <250710285+RatchetStuff@users.noreply.github.com>
Date:   Sun Sep 20 19:37:56 2026 +0800

    chore: Cleanup workflows and shell scripts

diff --git a/.github/workflows/prepare.yml b/.github/workflows/prepare.yml
--- a/.github/workflows/prepare.yml
+++ b/.github/workflows/prepare.yml
@@ -44,9 +44,9 @@ jobs:
                 if ! grep -q '^Failed to check updates for ' <<< "$output"; then
                   break
                 else
-                  echo 'Retrying...'
+                  echo "Update check failed! Retrying..."
                 fi
-                sleep 5
+                sleep 30
               done
             )
           done
@@ -94,7 +94,8 @@ jobs:
         run: |
           previous_tag=$(git tag --sort=-version:refname | head -n 1)
           if [ -z "$previous_tag" ]; then
-            echo "No previous tag found" && exit 1
+            echo "No previous tag found."
+            exit 1
           fi
           echo "tag=$previous_tag" >> "$GITHUB_OUTPUT"
 
@@ -114,7 +115,7 @@ jobs:
           pack_version: ${{ steps.version.outputs.version }}
           previous_tag: ${{ steps.previous_tag.outputs.tag }}
         run: |
-          find versions -type f -name "pack.toml" -print0 | while IFS= read -r -d '' filepath; do
+          find versions -type f -name 'pack.toml' -print0 | while IFS= read -r -d '' filepath; do
             dir=$(dirname "$filepath")
             if [ -n "$previous_tag" ] && git diff --quiet "$previous_tag" -- "$dir"; then
               continue
